# Dockerfile.client
FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install grpcio grpcio-tools

# Генерация Python-файлов из .proto
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. glossary.proto

CMD ["python", "client.py"]
